### ISSUE TITLE
Out of memory error when predicting

### ISSUE THREAD

**Issue by kulkarnikeerti** [luca-medeiros/lang-segment-anything#93]
### Full runnable code or full changes you made:

```
def read_image():
    image_pil = Image.open("image1.jpg").convert("RGB")

PROMPTS = ['light', 'box', 'table', 'chair', 'truck', 'floor',
               'wall', 'object', 'ceiling', 'barrier', 'sign', 'person', 'boxes',
               'obstacle', 'bicycle', 'bench', 'traffic light', 'animal',
               'pole', 'chair', 'container', 'train', 'shipment', 'barrel',
               'cart', 'bus', 'cardboard', 'bottle', 'car']
IMAGES = ['image1', 'image2', 'image3', 'image4', ....]

model = LangSAM()

for img in IMAGES:
    for text in PROMPTS:
        results = model.predict([image], [text_prompt])
    ....
    ....
```

### What exact command you ran:

Hi @luca-medeiros  Thanks for the great work. 

I tried to create masks for different objects and save them further. But, I get the out-of-memory error  as shown below after running it for few images and few prompts. I tried to use the list format but I have other [issue](https://github.com/luca-medeiros/lang-segment-anything/issues/92) 

`torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 334.00 MiB. GPU 0 has a total capacity of 7.75 GiB of which 273.31 MiB is free. Including non-PyTorch memory, this process has 7.41 GiB memory in use. Of the allocated memory 7.00 GiB is allocated by PyTorch, and 289.29 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
`

And the same code runs without any issues with SAM1. Why is there a memory problem with SAM2?

Could you please help me with this? 
Thanks in advance

### Expected behavior

It should generate without any issues

### Environment

- [ ] I'm using the latest version!
- [ ] It's not a user-side mistake!

**Comment by luca-medeiros** [comment]
I've replied about the multi-query issue #92.
Now, about the OOM, it's hard to tell without actually testing it. It would help to know hardware specs, image size, etc.

You should report in more detail with the output logs.

**Comment by kulkarnikeerti** [comment]
This is the full error log. Mentioned loop runs for few iterations and afterwards the memory is full. And image size is  `(1920, 1080)`. I am running in Ubuntu 24.04, Cuda: 12.4 and NVIDIA GeForce RTX 4060

```
Traceback (most recent call last):
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 752, in forward
    output = MultiScaleDeformableAttentionFunction.apply(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 114, in forward
    output = MultiScaleDeformableAttention.ms_deform_attn_forward(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ms_deform_attn_forward'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/keerti/git/lang-segment-anything-main/generate_masks.py", line 183, in <module>
    generate_masks(dataset_dir, masks_dir, data_list, str(text_prompt))
  File "/home/keerti/git/lang-segment-anything-main/generate_masks.py", line 157, in generate_masks
    results = model.predict([image], [text_prompt])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/git/lang-segment-anything-main/lang_sam/lang_sam.py", line 42, in predict
    gdino_results = self.gdino.predict(images_pil, texts_prompt, box_threshold, text_threshold)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/git/lang-segment-anything-main/lang_sam/models/gdino.py", line 40, in predict
    outputs = self.model(**inputs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 3023, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 2360, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 1753, in forward
    (vision_features, text_features), attentions = encoder_layer(
                                                   ^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 1280, in forward
    (vision_features, vision_deformable_attn) = self.deformable_layer(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 1146, in forward
    hidden_states, attn_weights = self.self_attn(
                                  ^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 762, in forward
    output = multi_scale_deformable_attention(value, spatial_shapes, sampling_locations, attention_weights)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keerti/lang_sam2/lib/python3.12/site-packages/transformers/models/grounding_dino/modeling_grounding_dino.py", line 617, in multi_scale_deformable_attention
    (torch.stack(sampling_value_list, dim=-2).flatten(-2) * attention_weights)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 328.00 MiB. GPU 0 has a total capacity of 7.75 GiB of which 231.31 MiB is free. Including non-PyTorch memory, this process has 7.45 GiB memory in use. Of the allocated memory 6.79 GiB is allocated by PyTorch, and 551.11 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

```

**Comment by luca-medeiros** [comment]
The error also mentions `AttributeError: 'NoneType' object has no attribute 'ms_deform_attn_forward'` which is strange.

Have you observed this happening with multiple images or have you tried running it on the image that raises the error alone? Would be nice to actually check if the issue is a single data sample.

**Comment by kulkarnikeerti** [comment]
Yes, I have already checked it. I ran the same set of images individually and there is no issue. But, with multiple images I have this issue.

**Comment by luca-medeiros** [comment]
LangSAM does not store results in memory. Seems the issue comes from grounding dino.
Wanna try upgrading your transformers library and trying again?

**Comment by kulkarnikeerti** [comment]
Updated transformers from `4.44.2`to latest version `4.48.3` but no luck.

> LangSAM does not store results in memory. Seems the issue comes from grounding dino. Wanna try upgrading your transformers library and trying again?

**Comment by luca-medeiros** [comment]
It would help to have the exact script used.

**Comment by kulkarnikeerti** [comment]
You can find the python file and the dataset here. Dataset folder contains the yaml file to be used. [https://drive.google.com/drive/folders/1CzBYdJu9YcKmC0kgkuSaEcJN0APceqP8?usp=sharing](url)

**Comment by kulkarnikeerti** [comment]
I was able to resolve it. Issue was that I was loading the model for each prediction, which increased the memory consumption and lead to OOM. I just had to load the model once at the beginning.
